
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { CircleDollarSign, LightbulbIcon, BarChart4, Target, TrendingUp } from "lucide-react";
import { useState } from "react";

// Mock tips data - would be generated by AI in production
const mockTips = [
  {
    id: 1,
    title: "Optimize Your Emergency Fund",
    description: "Consider keeping 3-6 months of expenses in a high-yield savings account to maximize interest while maintaining liquidity.",
    category: "Savings",
    icon: CircleDollarSign,
  },
  {
    id: 2,
    title: "Rebalance Your Investment Portfolio",
    description: "Your stock allocation has drifted above your target. Consider rebalancing to maintain your desired risk profile.",
    category: "Investments",
    icon: BarChart4,
  },
  {
    id: 3,
    title: "Debt Reduction Strategy",
    description: "Focusing on your highest interest debt first while making minimum payments on others could save you $1,250 in interest over the next year.",
    category: "Debt",
    icon: TrendingUp,
  },
  {
    id: 4,
    title: "Retirement Contribution",
    description: "Increasing your 401(k) contribution by just 1% could add an additional $42,000 to your retirement fund over 20 years.",
    category: "Retirement",
    icon: Target,
  },
];

const FinancialTips = () => {
  const [currentTip, setCurrentTip] = useState(0);
  
  const nextTip = () => {
    setCurrentTip((prev) => (prev + 1) % mockTips.length);
  };
  
  const prevTip = () => {
    setCurrentTip((prev) => (prev - 1 + mockTips.length) % mockTips.length);
  };
  
  const tip = mockTips[currentTip];
  
  return (
    <Card className="glass-card">
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <LightbulbIcon className="h-5 w-5 text-wealth-accent" />
            <CardTitle className="text-xl">AI Financial Insights</CardTitle>
          </div>
          <span className="text-xs text-muted-foreground">
            Tip {currentTip + 1} of {mockTips.length}
          </span>
        </div>
        <CardDescription>Personalized financial advice based on your data</CardDescription>
      </CardHeader>
      <CardContent className="py-4">
        <div className="flex flex-col items-start">
          <div className="flex items-center gap-2 mb-2">
            <span className="bg-wealth-accent/10 p-2 rounded-full">
              <tip.icon className="h-5 w-5 text-wealth-accent" />
            </span>
            <span className="text-sm font-medium text-wealth-accent">{tip.category}</span>
          </div>
          <h3 className="text-lg font-semibold mb-2">{tip.title}</h3>
          <p className="text-muted-foreground">{tip.description}</p>
        </div>
      </CardContent>
      <CardFooter className="flex justify-between pt-2">
        <Button variant="outline" size="sm" onClick={prevTip}>
          Previous
        </Button>
        <Button className="bg-wealth-accent hover:bg-wealth-accent/90" size="sm" onClick={nextTip}>
          Next Tip
        </Button>
      </CardFooter>
    </Card>
  );
};

export default FinancialTips;
